# Generated by Django 5.1.3 on 2024-12-17 07:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csvManager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.IntegerField()),
                ('english', models.CharField(max_length=100)),
                ('japanese', models.CharField(max_length=100)),
                ('text', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='words', to='csvManager.text')),
            ],
        ),
    ]
