# Generated by Django 5.1.3 on 2024-12-17 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('csvManager', '0002_word'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='word',
            name='text',
        ),
    ]
