# Generated by Django 5.1.3 on 2024-12-17 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('csvManager', '0004_nounitword_delete_word'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nounitword',
            name='text',
        ),
    ]
