# Generated by Django 5.1.3 on 2024-12-17 07:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csvManager', '0005_remove_nounitword_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='nounitword',
            name='text',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='words', to='csvManager.text'),
            preserve_default=False,
        ),
    ]
