# Generated by Django 5.1.3 on 2024-11-23 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeruJun2',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('word', models.CharField(max_length=100)),
                ('meaning', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='DeruJun3',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('word', models.CharField(max_length=100)),
                ('meaning', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='DeruJun4',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('word', models.CharField(max_length=100)),
                ('meaning', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='DeruJun5',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('word', models.CharField(max_length=100)),
                ('meaning', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='DeruJunPre2',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('word', models.CharField(max_length=100)),
                ('meaning', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='JuniorHighEnglish1000',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('word', models.CharField(max_length=100)),
                ('meaning', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SystemEnglish',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('word', models.CharField(max_length=100)),
                ('meaning', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Target1900',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('word', models.CharField(max_length=100)),
                ('meaning', models.CharField(max_length=100)),
            ],
        ),
    ]
