# Generated by Django 5.1.3 on 2024-11-24 02:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EnglishWordTest', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='derujun2',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='derujun3',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='derujun4',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='derujun5',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='derujunpre2',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='juniorhighenglish1000',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='systemenglish',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='target1900',
            options={'managed': False},
        ),
    ]
