# Generated by Django 5.1.3 on 2024-12-17 03:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EnglishWordTest', '0002_alter_derujun2_options_alter_derujun3_options_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='derujun2',
            table='DeruJun2',
        ),
        migrations.AlterModelTable(
            name='derujun3',
            table='DeruJun3',
        ),
        migrations.AlterModelTable(
            name='derujun4',
            table='DeruJun4',
        ),
        migrations.AlterModelTable(
            name='derujun5',
            table='DeruJun5',
        ),
        migrations.AlterModelTable(
            name='derujunpre2',
            table='DeruJunPre2',
        ),
        migrations.AlterModelTable(
            name='juniorhighenglish1000',
            table='JuniorHighEnglish1000',
        ),
        migrations.AlterModelTable(
            name='systemenglish',
            table='SystemEnglish',
        ),
        migrations.AlterModelTable(
            name='target1900',
            table='Target1900',
        ),
    ]
